package in.co.capgemini;

import java.util.Scanner;

class InvalidInputException extends Exception {
	
	public InvalidInputException(String message) {
		super(message);
	}
}

class FactorialExceedException extends Exception {
	
	public FactorialExceedException(String message) {
		super(message);
	}
}
public class Factorial {
	
	public int getFactorial(int number) throws InvalidInputException, FactorialExceedException{
		
		int i, factorial = 1;
		
		for(i = 1; i <= number; i++) {
			factorial *= i;
		}
		
	}
	
	public static void main(String args[]) {
		
		Factorial factorial = new Factorial();
		Scanner scanner = new Scanner(System.in);
		System.out.println("Ener hte number: ");
		int number = scanner.nextInt();
		int answer;
		
		try {
			answer = factorial.getFactorial(number);
			System.out.println("The factorial of " + number + " is " + answer);
		} catch (InvalidInputException e) {
			//handle exception
			e.printStackTrace();
		} catch(FactorialExceedException e) {
			e.printStackTrace();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}

}
